BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Hint] ALTER COLUMN [hint] NVARCHAR(4000) NOT NULL;

-- AlterTable
ALTER TABLE [dbo].[Hint_Bullet] ALTER COLUMN [bullet] NVARCHAR(4000) NOT NULL;

-- AlterTable
ALTER TABLE [dbo].[Note] ALTER COLUMN [note] NVARCHAR(4000) NOT NULL;

-- AlterTable
ALTER TABLE [dbo].[Task] ALTER COLUMN [task] NVARCHAR(4000) NOT NULL;
ALTER TABLE [dbo].[Task] ALTER COLUMN [answer] NVARCHAR(4000) NOT NULL;
ALTER TABLE [dbo].[Task] ALTER COLUMN [comments] NVARCHAR(4000) NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
